version: 2.1

parameters:
  dart-tag:
    type: string
    default: "latest"

orbs:
  tailscale: threecomma/circleci-tailscale@2.2.0

jobs:
  scan-and-report:
    docker:
      - image: dart:<<pipeline.parameters.dart-tag>>

    steps:
      - checkout

      - run:
          name: Setup Python
          command: |
            curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
            curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list
            apt update
            apt install -y python3 tailscale

      - run:
          name: Run Dart Analyze
          command: dart analyze > dart_analyze.txt || true

      - run:
          name: Dart Analyze to SARIF
          command: |
            curl -sSL https://raw.githubusercontent.com/advanced-security/dart-analyzer-sarif/main/dart_analyzer_sarif.py > dart-analyzer-sarif
            python3 dart-analyzer-sarif dart_analyze.txt dart_analyze.sarif $HOME --repo-uri <<pipeline.project.git_url>> --branch <<pipeline.git.branch>> --revision-id <<pipeline.git.revision>>

      - tailscale/connect
      - run:
          name: Upload SARIF report to DeepSource
          environment:
            DEEPSOURCE_DSN: $DEEPSOURCE_DSN
          command: |
            # Install the DeepSource CLI
            curl https://deepsource.io/cli | sh

            echo $DEEPSOURCE_DSN

            # Send the report to DeepSource
            ./bin/deepsource report --analyzer dart-analyze --analyzer-type community --value-file ./dart_analyze.sarif

workflows:
  scan-dart-analyze-workflow:
    jobs:
      - scan-and-report
